version: '3.8'

services:
  
  redis:
    image: redis:alpine
    command: [ "redis-server", "/redis.conf" ]
    volumes:
      - redis_data:/redis.conf
      - redis_data:/data
    networks:
      - backend
    deploy:
      restart_policy:
        condition: unless-stopped
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels==db"
  
  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_password
    deploy:
      restart_policy:
        condition: unless-stopped
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels==db"
          

secrets:
  db_password:
    file: secrets/db_password.txt

volumes:
  db_data:
  redis_data:

networks:
  backend:
  