version: '3.8'

services:
  
  platform:
    image: gcr.io/${PROJECT_ID}/platform:latest
    env_file:
      - config/dev.env
    ports:
      - 80:80
    networks:
      - backend
    deploy:
      placement:
        max_replicas_per_node: 2
        constraints:
          - node.labels.type==platform

  redis:
    image: gcr.io/${PROJECT_ID}/redis:latest
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==db
  
  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==db


  systemtests:
    image: gcr.io/${PROJECT_ID}/systemtests:latest
    env_file:
      - config/dev.env
    ports:
      - 8080:8080
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

volumes:
  postgres_data:

networks:
  backend:
